printWidth: 80 # 80
tabWidth: 2 # 2
useTabs: true # false
semi: true
singleQuote: false
trailingComma: none # none | es5 | all
bracketSpacing: true
jsxBracketSameLine: false # false
arrowParens: avoid # avoid | always
